name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - release/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache setup
        uses: actions/cache@v4
        with:
          path: ./*
          key: ${{ github.ref }}-${{ github.sha }}-setup


  build-and-push:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: Restore setup
        uses: actions/cache@v4
        with:
          path: ./*
          key: ${{ github.ref }}-${{ github.sha }}-setup

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,branch=main
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}
          labels: |
            type=raw,key=branch,value=${{ github.ref_name }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-tag-dev:
    needs: [ setup, build-and-push ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Clone target repository
        env:
          TARGET_REPO_PAT: ${{ secrets.CR_PAT }}
        run: |
          git clone https://x-access-token:${{ secrets.CR_PAT }}@github.com/VNxyz1/connect-u-deployment.git target-repo
          cd target-repo

      - name: Update image tag
        run: |
          cd target-repo
          sed -i 's|image: ghcr.io/vnxyz1/connect-u-frontend:.*|image: ghcr.io/vnxyz1/connect-u-frontend:${{ github.ref_name }}|' connect-u/prod/argocd-conf/frontend-deployment.yaml

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          git add connect-u/prod/argocd-conf/frontend-deployment.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}"
          git push
